name: 'Setup Host'
description: 'Configures the host runner to run the build'

runs:
  using: "composite"
  steps:
    - name: Setup JDK11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
