name: Update Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup host
        uses: ./.github/actions/setup-host
        with:
          gradle-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Update Gradle Wrapper
        uses: gmazzo/update-gradle-wrapper-action@ignore-failure-2ndtime
        with:
          repo-token: ${{ secrets.AUTOMERGE_TOKEN }}
          labels: dependencies
          merge-method: squash
